import 'package:get/get.dart';

class Localization extends Translations {
  final Map<String, Map<String, String>>? json;
  Localization(this.json);
  @override
  Map<String, Map<String, String>> get keys =>
      json ??
      {
        "en": {
          "ACCESS_SETTINGS": "Access settings",
          "ADD": "Add",
          "ADD_MORE_PRODUCTS": "Add more products",
          "ALLERGENS": "Allergens",
          "AMOUNT": "Amount",
          "AND": "AND",
          "ARE_YOU_SURE": "Are you sure?",
          "ASK_FOR": "Ask for",
          "ASK_SOMETHING": "Ask something",
          "CANCEL": "Cancel",
          "CART": "Cart",
          "CART_IS_EMPTY": "Cart is empty",
          "CATEGORY_REPRESENTATION": "Category representation",
          "CELERY": "Celery",
          "CEREALS_CONTAINING_GLUTEN": "Cereals containing Gluten",
          "CHANGE_PASSCODE": "Change passcode",
          "CHOOSE_KIOSK_MODE": "Choose Kiosk mode",
          "CHOOSE_MENU": "Choose menu",
          "CHOOSE_SIZE": "Choose size",
          "CONCEPT": "Concept",
          "CONNECTION_CODE": "Connection code",
          "CONNECT_ERROR_PRINTER": "Couldn't Connect to the Printer",
          "CREATE_ORDER_FIRST": "Create order first",
          "CRUSTACEANS": "Crustanceans",
          "DATE": "DATE",
          "DELIVERY_TABLE": "DELIVERY AT TABLE",
          "DESK": "Desk",
          "DIVIDE_THE_ACCOUNT": "Divide the account",
          "DO_YOU_WANT_TO_ADD_TIP": "Do you want to add a tip to the waiter?",
          "DO_YOU_WANT_TO_EXIT_AN_APP": "Do you want to exit an app",
          "DRINKS": "Drinks",
          "EGGS": "Eggs",
          "ENABLE_CALL_TO_WAITER": "Enable call to waiter",
          "FISH": "Fish",
          "FOOD": "Food",
          "FRANCHISE_CODE": "Franchise code",
          "FRANCHISE_CODE_CANT_EMPTY": "Franchise code cant empty",
          "FROM": "From",
          "GRAND_TOTAL": "Grand Total",
          "GRID": "grid",
          "HELLO": "Hello",
          "HELP_WITH_THE_NAPKIN_RACK": "Help with then napkin rack",
          "HOME": "Home",
          "HOW_YOU_LIKE_TO_CUSTOMIZE": "How you like to customize ?",
          "INSTRUCTIONS": "Instructions",
          "INVOICE_NUMBER": "Invoice number",
          "IN_PROCESS": "in process...",
          "IP_ERROR_PRINTER": "Printer IP not specified",
          "KIOSK_MODE": "Kiosk mode",
          "LEGAL_NAME": "LEGAL NAME",
          "LIST": "list",
          "LOGIN": "Login to continue",
          "LOGOUT": "Logout",
          "LUPIN": "Lupin",
          "MILK": "Milk",
          "MODIFICATION": "Modification",
          "MODIFY_ORDER": "Modify a shipment",
          "MOLLUSCS": "Molluscs",
          "MULTIPLE_SAME_PRODUCTS_IN_CART": "Multiple same products in cart",
          "MUSTARD": "Mustard",
          "NEW": "New",
          "NFC": "Pay here, in pilarbox",
          "NO": "No",
          "NOTE_SELECT": "Note: You must select NUMBER extras",
          "NOTE_SELECT_DAILOG":
              "You must select NUMBER extras from CATEGORY_NAME",
          "NOTICE_TO_THE_WAITER": "Notify to the waiter",
          "NO_ITEMS": "No items",
          "NO_ORDER_PLACED": "No Order Placed yet",
          "NO_PRODUCT": "No product",
          "NO_THANKS": "No Thanks!",
          "NUTS": "Nuts",
          "OFF": "OFF",
          "OK": "ok",
          "OK_PAYMENT_METHODS": "Ok, Payment Methods",
          "ORDERID": "OrderID",
          "ORDERING_MODE": "Ordering mode",
          "ORDER_CANCELLED": "Order Cancelled",
          "ORDER_COMPLETED": "Order Completed",
          "ORDER_CONFIRMED": "Order Confirmed",
          "ORDER_ID": "Order ID",
          "ORDER_IS_CANCELLED": "Your order is cancelled..",
          "ORDER_PENDING": "Order Pending",
          "ORDER_RECEIVED": "ORDER RECEIVED",
          "OTHER": "Other",
          "PAID_OUT": "Paid out",
          "PASSCODE": "Passcode",
          "PASSWORD_CANT_EMPTY": "Password cant empty",
          "PAY_CHECKOUT": "PAY AT CHECKOUT",
          "PAY_CHECKOUT_DELIVERY_TABLE":
              "Pay at Checkout and Delivery At Table",
          "PAY_CHECKOUT_PICK_PRODUCT": "Pay at Checkout and Pick up Product",
          "PAY_IN_CASH": "Pay in cash",
          "PAY_TABLE": "PAY AT TABLE",
          "PAY_TABLE_DELIVERY_TABLE": "Pay at Table and Delivery at Table",
          "PAY_WHEN_YOU_MAKE_THE_COMMAND_KIOSK TYPE":
              "Pay when you make the command (KIOSK TYPE)",
          "PAY_WITH_DATAPHONE": "Pay with Dataphone",
          "PAY_WITH_QR": "Pay with QR",
          "PEANUTS": "Peanuts",
          "PHONE_NUMBER": "PHONE NUMBER",
          "PICK_PRODUCT": "PICK UP PRODUCT",
          "PLACE_ORDER": "Place order",
          "PLEASE_ENTER_VALID_PASSWORD":
              "Password length at least 6 characters",
          "PLEASE_SELECT_MENU": "Please select menu",
          "PRICE": "Price",
          "PRINTER_IP_ADDRESS": "Printer's IP address",
          "REPEAT_LAST": "Repeat last",
          "REQUEST": "Request",
          "REQUEST_NAPKINS": "Request napkings",
          "RESET_CATEGORY": "Reset Category",
          "RETURN": "Return",
          "SELECTED_PRODUCTS": "Selected Products",
          "SELECT_COLOR": "Select color",
          "SELECT_EXTRA_FIRST": "Select EXTRA first",
          "SELECT_MENU": "Select menu",
          "SERVER_NOT_RESPONDING": "Server not responding",
          "SESAME_SEEDS": "Sesame seeds",
          "SESSION EXPIRED": "Session Expired",
          "SOYA": "Soya",
          "SUBMIT": "Submit",
          "SUB_TOTAL": "Sub Total",
          "SULPHER_DI_OXIDE": "Sulpher-di-oxide",
          "TABLE": "TABLE",
          "TABLE_CAPACITY": "Table capacity",
          "TABLE_NUMBER": "Table number",
          "TABLE_NUMBER_CANT_EMPTY": "Table number cant empty",
          "TAX_BASE_PRINTER": "I.V.A/ TAX BASE 10.00%",
          "THANK_YOU_VERY_MUCH": "Thank you very much,",
          "TIME": "TIME",
          "TOTAL": "Total",
          "TOTAL_SELECTION": "Total Selection",
          "TOTAL_VAT_INCLUDED": "Total 10% vat included",
          "TO_CALL": "To Call",
          "TO_PAY": "To pay",
          "UPDATE": "Update",
          "USER_CANT_CHANGE_ORDER": "Please wait untill the order is confirmed",
          "USER_CANT_CHANGE_PAYMENT":
              "Please wait untill the payment is complete",
          "VALIDATE_PAYMENT_OR_COMMANDS_BY_WAITER":
              "Validate payment / Commands by waiter",
          "VAT_INCLUDE_TOTAL": "VAT include Total",
          "VIEW_ALL": "View all",
          "WAITER_WARNED": "Waiter Notified",
          "WAY_TO_PAY": "WAY TO PAY",
          "WE_WAIT_FOR_YOU_SOON": "We hope to see you soon.",
          "YES": "Yes",
          "YOUR_ORDER_IS": "Your order is",
          "YOUR_PAYMENT_IS": "Your payment is"
        },
        "es": {
          "ACCESS_SETTINGS": "Configuración de acceso",
          "ADD": "Añadir",
          "ADD_MORE_PRODUCTS": "Añadir más productos",
          "ALLERGENS": "Alérgenos",
          "AMOUNT": "Monto",
          "AND": "Y",
          "ARE_YOU_SURE": "¿Está seguro?",
          "ASK_FOR": "ENVIAR",
          "ASK_SOMETHING": "Preguntar algo",
          "CANCEL": "Cancelar",
          "CART": "Carrito",
          "CART_IS_EMPTY": "El carrito está vacio",
          "CATEGORY_REPRESENTATION": "Categoría",
          "CELERY": "Celery",
          "CEREALS_CONTAINING_GLUTEN": "Cereals containing Gluten",
          "CHANGE_PASSCODE": "Cambiar contraseña",
          "CHOOSE_KIOSK_MODE": "Escoger modo Kiosk ",
          "CHOOSE_MENU": "Elegir menú",
          "CHOOSE_SIZE": "Elegir tamaño",
          "CONCEPT": "Concepto",
          "CONNECTION_CODE": "Código de conexión",
          "CONNECT_ERROR_PRINTER": "No se pudo conectar a la impresora",
          "CREATE_ORDER_FIRST": "Crear pedido primero",
          "CRUSTACEANS": "Crustanceans",
          "DATE": "FECHA",
          "DELIVERY_TABLE": "ENTREGA EN MESA",
          "DESK": "MESA",
          "DIVIDE_THE_ACCOUNT": "Dividir la cuenta",
          "DO_YOU_WANT_TO_ADD_TIP": "¿Quieres agregar una propina al mesero?",
          "DO_YOU_WANT_TO_EXIT_AN_APP": "¿Desea salir de la aplicación?",
          "DRINKS": "Bebidas",
          "EGGS": "Eggs",
          "ENABLE_CALL_TO_WAITER": "Habilitar llamada al camarero",
          "FISH": "Fish",
          "FOOD": "Comida",
          "FRANCHISE_CODE": "Código de franquicia",
          "FRANCHISE_CODE_CANT_EMPTY":
              "El código de franquicia no puede estar vacío",
          "FROM": "De",
          "GRAND_TOTAL": "Total",
          "GRID": "red",
          "HELLO": "Hola",
          "HELP_WITH_THE_NAPKIN_RACK": "Ayuda con el servilletero",
          "HOME": "Inicio",
          "HOW_YOU_LIKE_TO_CUSTOMIZE": "¿Cómo te gusta personalizarlo?",
          "INSTRUCTIONS": "Instrucciones",
          "INVOICE_NUMBER": "Número de factura",
          "IN_PROCESS": "En proceso...",
          "IP_ERROR_PRINTER": "IP de la impresora no especificada",
          "KIOSK_MODE": "Modo Kiosk",
          "LEGAL_NAME": "NOMBRE LEGAL",
          "LIST": "lista",
          "LOGIN": "Accede para continuar",
          "LOGOUT": "Desconectar",
          "LUPIN": "Lupin",
          "MILK": "Milk",
          "MODIFICATION": "Modificación",
          "MODIFY_ORDER": "Enviar comanda",
          "MOLLUSCS": "Molluscs",
          "MULTIPLE_SAME_PRODUCTS_IN_CART":
              "Varis productos repetidos en el carrito",
          "MUSTARD": "Mustard",
          "NEW": "Nuevo",
          "NFC": "Pagar aquí en Pilarbox",
          "NO": "No",
          "NOTE_SELECT": "Nota: Debes seleccionar NUMBER extras",
          "NOTE_SELECT_DAILOG":
              "Debes seleccionar NUMBER extras de CATEGORY_NAME",
          "NOTICE_TO_THE_WAITER": "Notificar al camarero",
          "NO_ITEMS": "No hay artículos",
          "NO_ORDER_PLACED": "Aún no se ha realizado ningún pedido",
          "NO_PRODUCT": "No hay productos",
          "NO_THANKS": "¡No, gracias!",
          "NUTS": "Nuts",
          "OFF": "APAGADA",
          "OK": "ok",
          "OK_PAYMENT_METHODS": "Vale, métodos de pago",
          "ORDERID": "Solicitar ID",
          "ORDERING_MODE": "Modo de pedido",
          "ORDER_CANCELLED": "Pedido cancelado",
          "ORDER_COMPLETED": "Pedido completado",
          "ORDER_CONFIRMED": "Pedido confirmado",
          "ORDER_ID": "ID del pedido",
          "ORDER_IS_CANCELLED": "Su pedido está cancelado",
          "ORDER_PENDING": "Pedido pendiente",
          "ORDER_RECEIVED": "ORDEN RECIBIDA",
          "OTHER": "Otro",
          "PAID_OUT": "Pagado",
          "PASSCODE": "Contraseña",
          "PASSWORD_CANT_EMPTY": "La contraseña no puede estar vacía",
          "PAY_CHECKOUT": "PAGAR EN EL MOSTRADOR",
          "PAY_CHECKOUT_DELIVERY_TABLE":
              "Pague en el mostrador y espere a que le entreguen su pedido en la mesa",
          "PAY_CHECKOUT_PICK_PRODUCT":
              "Pague en el mostrador y recoja su producto",
          "PAY_IN_CASH": "Pagar en efectivo",
          "PAY_TABLE": "PAGAR EN MESA",
          "PAY_TABLE_DELIVERY_TABLE": "Paga en mesa y entrega en mesa",
          "PAY_WHEN_YOU_MAKE_THE_COMMAND_KIOSK TYPE":
              "Pague cuando haga el pedido (TIPO KIOSCO)",
          "PAY_WITH_DATAPHONE": "Pagar con datáfono",
          "PAY_WITH_QR": "Pagar con QR",
          "PEANUTS": "Peanuts",
          "PHONE_NUMBER": "NÚMERO DE TELÉFONO",
          "PICK_PRODUCT": "RECOGER EL PRODUCTO",
          "PLACE_ORDER": "Realizar pedido",
          "PLEASE_ENTER_VALID_PASSWORD":
              "Longitud de la contraseña de al menos 6 caracteres",
          "PLEASE_SELECT_MENU": "Por favor seleccione el menú",
          "PRICE": "Precio",
          "PRINTER_IP_ADDRESS": "Dirección IP de la impresora",
          "REPEAT_LAST": "Repite el último",
          "REQUEST": "Pedir",
          "REQUEST_NAPKINS": "Pedir servilletas",
          "RESET_CATEGORY": "Restablecer categoría",
          "RETURN": "Volver",
          "SELECTED_PRODUCTS": "Productos seleccionados",
          "SELECT_COLOR": "Seleccionar color",
          "SELECT_EXTRA_FIRST": "Seleccione EXTRA primero",
          "SELECT_MENU": "Seleccionar menú",
          "SERVER_NOT_RESPONDING": "El servidor no responde",
          "SESAME_SEEDS": "Sesame seeds",
          "SESSION EXPIRED": "Sesión caducada",
          "SOYA": "Soya",
          "SUBMIT": "Enviar",
          "SUB_TOTAL": "Sub Total",
          "SULPHER_DI_OXIDE": "Sulpher-di-oxide",
          "TABLE": "MESA",
          "TABLE_CAPACITY": "Capacidad de la mesa",
          "TABLE_NUMBER": "Número de mesa",
          "TABLE_NUMBER_CANT_EMPTY": "El número de mesa no puede estar vacío",
          "TAX_BASE_PRINTER": "I.V.A/ TAX BASE 10.00%",
          "THANK_YOU_VERY_MUCH": "Thank you very much,",
          "TIME": "TIEMPO",
          "TOTAL": "Total",
          "TOTAL_SELECTION": "Selección total",
          "TOTAL_VAT_INCLUDED": "Total 10% de iva incluido",
          "TO_CALL": "Llamar",
          "TO_PAY": "Pagar",
          "UPDATE": "Actualizar",
          "USER_CANT_CHANGE_ORDER": "Espere hasta que se confirme el pedido",
          "USER_CANT_CHANGE_PAYMENT": "Espere hasta que se complete el pago",
          "VALIDATE_PAYMENT_OR_COMMANDS_BY_WAITER":
              "Validar pago / Comandar con camarero",
          "VAT_INCLUDE_TOTAL": "IVA total incluido",
          "VIEW_ALL": "Ver todo",
          "WAITER_WARNED": "Camarero notificado",
          "WAY_TO_PAY": "FORMA DE PAGAR",
          "WE_WAIT_FOR_YOU_SOON": "Te esperamos pronto",
          "YES": "Sí",
          "YOUR_ORDER_IS": "Su pedido está",
          "YOUR_PAYMENT_IS": "Su pago está"
        }
      };
}
