import 'package:get/get.dart';

class Localization extends Translations {
  final Map<String, Map<String, String>>? json;
  Localization(this.json);
  @override
  Map<String, Map<String, String>> get keys =>
      json ??
      {
        'en': {
          "ACCESS_SETTINGS": "Access settings",
          "ADD": "Add",
          "ADD_MORE_PRODUCTS": "Add more products",
          "ALLERGENS": "Allergens",
          "ARE_YOU_SURE": "Are you sure?",
          "ASK_FOR": "Ask for",
          "ASK_SOMETHING": "Ask something",
          "CANCEL": "Cancel",
          "CART": "Cart",
          "CART_IS_EMPTY": "Cart is empty",
          "CATEGORY_REPRESENTATION": "Category representation",
          "CHANGE_PASSCODE": "Change passcode",
          "CHOOSE_MENU": "Choose menu",
          "CHOOSE_SIZE": "Choose size",
          "CONNECTION_CODE": "Connection code",
          "CREATE_ORDER_FIRST": "Create order first",
          "DESK": "Desk",
          "DIVIDE_THE_ACCOUNT": "Divide the account",
          "DO_YOU_WANT_TO_EXIT_AN_APP": "Do you want to exit an app",
          "DRINKS": "Drinks",
          "ENABLE_CALL_TO_WAITER": "Enable call to waiter",
          "FOOD": "Food",
          "FRANCHISE_CODE": "Franchise code",
          "FRANCHISE_CODE_CANT_EMPTY": "Franchise code cant empty",
          "FROM": "From",
          "GRAND_TOTAL": "Grand Total",
          "GRID": "grid",
          "HELLO": "Hello",
          "HELP_WITH_THE_NAPKIN_RACK": "Help with then napkin rack",
          "HOME": "Home",
          "HOW_YOU_LIKE_TO_CUSTOMIZE": "How you like to customize ?",
          "INSTRUCTIONS": "Instructions",
          "IN_PROCESS": "in process...",
          "LIST": "list",
          "LOGIN": "Login to continue",
          "LOGOUT": "Logout",
          "MODIFY_ORDER": "Modify a shipment",
          "MULTIPLE_SAME_PRODUCTS_IN_CART": "Multiple same products in cart",
          "NEW": "New",
          "NFC": "Pay here, in pilarbox",
          "NO": "No",
          "NOTICE_TO_THE_WAITER": "Notify to the waiter",
          "NO_ITEMS": "No items",
          "NO_PRODUCT": "No product",
          "OK": "ok",
          "OK_PAYMENT_METHODS": "Ok, Payment Methods",
          "ORDERING_MODE": "Ordering mode",
          "ORDER_CANCELLED": "Order Cancelled",
          "ORDER_COMPLETED": "Order Completed",
          "ORDER_CONFIRMED": "Order Confirmed",
          "ORDER_ID": "Order ID",
          "ORDER_IS_CANCELLED": "Your order is cancelled..",
          "ORDER_PENDING": "Order Pending",
          "OTHER": "Other",
          "PAID_OUT": "Paid out",
          "PASSCODE": "Passcode",
          "PASSWORD_CANT_EMPTY": "Password cant empty",
          "PAY_IN_CASH": "Pay in cash",
          "PAY_WHEN_YOU_MAKE_THE_COMMAND_KIOSK TYPE":
              "Pay when you make the command (KIOSK TYPE)",
          "PAY_WITH_CARD": "Pay with dataphone",
          "PLACE_ORDER": "Place order",
          "PLEASE_ENTER_VALID_PASSWORD":
              "Password length at least 6 characters",
          "PLEASE_SELECT_MENU": "Please select menu",
          "REPEAT_LAST": "Repeat last",
          "REQUEST": "Request",
          "REQUEST_NAPKINS": "Request napkins",
          "RESET_CATEGORY": "Reset Category",
          "RETURN": "Return",
          "SELECTED_PRODUCTS": "Selected Products",
          "SELECT_COLOR": "Select color",
          "SELECT_MENU": "Select menu",
          "SERVER_NOT_RESPONDING": "Server not responding",
          "SESSION EXPIRED": "Session Expired",
          "SUBMIT": "Submit",
          "SUB_TOTAL": "Sub Total",
          "TABLE_CAPACITY": "Table capacity",
          "TABLE_NUMBER": "Table number",
          "TABLE_NUMBER_CANT_EMPTY": "Table number cant empty",
          "THANK_YOU_VERY_MUCH": "Thank you very much,",
          "TOTAL": "Total",
          "TOTAL_SELECTION": "Total Selection",
          "TO_CALL": "To Call",
          "TO_PAY": "To pay",
          "UPDATE": "Update",
          "VALIDATE_PAYMENT_OR_COMMANDS_BY_WAITER":
              "Validate payment / Commands by waiter",
          "VAT_INCLUDE_TOTAL": "VAT include Total",
          "VIEW_ALL": "View all",
          "WE_WAIT_FOR_YOU_SOON": "We hope to see you soon.",
          "YES": "Yes",
          "YOUR_ORDER_IS": "Your order is",
          "YOUR_PAYMENT_IS": "Your payment is",
          "TOTAL_VAT_INCLUDED": "Total 10% vat included",
          "KIOSK_MODE": "Kiosk mode",
          "CHOOSE_KIOSK_MODE": "Choose Kiosk mode",
          "PRINTER_IP_ADDRESS": "Printer's IP address",
          "PAY_CHECKOUT_PICK_PRODUCT": "Pay at Checkout and Pick up Product",
          "PAY_TABLE_DELIVERY_TABLE": "Pay at Table and Delivery at Table",
          "OFF": "OFF",
          "PAY_CHECKOUT_DELIVERY_TABLE":
              "Pay at Checkout and Delivery At Table",
          "PAY_CHECKOUT": "PAY AT CHECKOUT",
          "PAY_TABLE": "PAY AT TABLE",
          "PICK_PRODUCT": "PICK UP PRODUCT",
          "DELIVERY_TABLE": "DELIVERY AT TABLE",
          "AND": "AND",
          "CONNECT_ERROR_PRINTER": "Couldn\'t Connect to the Printer",
          "IP_ERROR_PRINTER": "Printer IP not specified",
          "USER_CANT_CHANGE_PAYMENT":
              "Please wait untill the order is confirmed",
          "USER_CANT_CHANGE_ORDER":
              "Please wait untill the payment is complete",
          "NO_ORDER_PLACED": "No Order Placed yet",
          "MODIFICATION": "Modification",
          "ORDERID": "OrderID",
          "DATE": "DATE",
          "TIME": "TIME",
          "PHONE_NUMBER": "PHONE NUMBER",
          "LEGAL_NAME": "LEGAL NAME",
          "INVOICE_NUMBER": "Invoice number",
          "CONCEPT": "Concept",
          "PRICE": "Price",
          "AMOUNT": "Amount",
          "TAX_BASE_PRINTER": "I.V.A/ TAX BASE 10.00%",
          "TABLE": "TABLE",
          "WAY_TO_PAY": "WAY TO PAY",
          "ORDER_RECEIVED": "ORDER RECEIVED",
        },
        'es': {
          "ACCESS_SETTINGS": "Configuración de acceso",
          "ADD": "Añadir",
          "ADD_MORE_PRODUCTS": "Añadir más productos",
          "ALLERGENS": "Alergenos",
          "ARE_YOU_SURE": "¿Está seguro?",
          "ASK_FOR": "Preguntar por",
          "ASK_SOMETHING": "Preguntar algo",
          "CANCEL": "Cancelar",
          "CART": "Carro",
          "CART_IS_EMPTY": "El carro está vacío",
          "CATEGORY_REPRESENTATION": "Representación de categoría",
          "CHANGE_PASSCODE": "Cambiar código de acceso",
          "CHOOSE_MENU": "Seleccione el menú",
          "CHOOSE_SIZE": "Elegir el tamaño",
          "CONNECTION_CODE": "Código de conexión",
          "CREATE_ORDER_FIRST": "Crear orden primero",
          "DESK": "Escritorio",
          "DIVIDE_THE_ACCOUNT": "Dividir la cuenta",
          "DO_YOU_WANT_TO_EXIT_AN_APP": "¿Desea salir de una aplicación?",
          "DRINKS": "Bebidas",
          "ENABLE_CALL_TO_WAITER": "Habilitar llamada a camarero",
          "FOOD": "Alimentos",
          "FRANCHISE_CODE": "Código de franquicia",
          "FRANCHISE_CODE_CANT_EMPTY": "Código de franquicia vacío",
          "FROM": "De",
          "GRAND_TOTAL": "Total Total",
          "GRID": "red",
          "HELLO": "Hello",
          "HELP_WITH_THE_NAPKIN_RACK": "Ayuda con el bastidor de la servilleta",
          "HOME": "Casa",
          "HOW_YOU_LIKE_TO_CUSTOMIZE": "¿Cómo le gusta personalizar?",
          "INSTRUCTIONS": "Instrucciones",
          "IN_PROCESS": "en proceso ...",
          "LIST": "lista",
          "LOGIN": "Iniciar sesión para continuar",
          "LOGOUT": "Cierre",
          "MODIFY_ORDER": "Modificar un envío",
          "MULTIPLE_SAME_PRODUCTS_IN_CART":
              "Varios mismos productos en el carro",
          "NEW": "Nuevo",
          "NFC": "Pagar aquí, en pilarbox",
          "NO": "No",
          "NOTICE_TO_THE_WAITER": "Notificar al camarero",
          "NO_ITEMS": "Sin elementos",
          "NO_PRODUCT": "Ningún producto",
          "OK": "Ok",
          "OK_PAYMENT_METHODS": "Aceptar, Métodos de pago",
          "ORDERING_MODE": "Modo de pedido",
          "ORDER_CANCELLED": "Pedido cancelado",
          "ORDER_COMPLETED": "Pedido completado",
          "ORDER_CONFIRMED": "Orden confirmada",
          "ORDER_ID": "ID de pedido",
          "ORDER_IS_CANCELLED": "Su pedido se cancela.",
          "ORDER_PENDING": "Pendiente de pedido",
          "OTHER": "Otros",
          "PAID_OUT": "Pagada fuera",
          "PASSCODE": "Código de acceso",
          "PASSWORD_CANT_EMPTY": "Contraseña no puede estar vacía",
          "PAY_IN_CASH": "Pago en efectivo",
          "PAY_WHEN_YOU_MAKE_THE_COMMAND_KIOSK TYPE":
              "Pagar al hacer el comando (KIOSK TYPE)",
          "PAY_WITH_CARD": "Pagar con datáfono",
          "PLACE_ORDER": "Orden de lugar",
          "PLEASE_ENTER_VALID_PASSWORD":
              "Longitud de contraseña de al menos 6 caracteres",
          "PLEASE_SELECT_MENU": "Seleccione el menú",
          "REPEAT_LAST": "Repetir la última",
          "REQUEST": "Solicitud",
          "REQUEST_NAPKINS": "Napkings de solicitud",
          "RESET_CATEGORY": "Restablecer categoría",
          "RETURN": "Retorno",
          "SELECTED_PRODUCTS": "Productos seleccionados",
          "SELECT_COLOR": "Seleccionar color",
          "SELECT_MENU": "Seleccione el menú",
          "SERVER_NOT_RESPONDING": "El servidor no responde",
          "SESSION EXPIRED": "Sesión caducada",
          "SUBMIT": "Presentar",
          "SUB_TOTAL": "Subtotal",
          "TABLE_CAPACITY": "Capacidad de tabla",
          "TABLE_NUMBER": "Número de cuadro",
          "TABLE_NUMBER_CANT_EMPTY": "Número de tabla no",
          "THANK_YOU_VERY_MUCH": "Muchas gracias,",
          "TOTAL": "Total",
          "TOTAL_SELECTION": "Selección total",
          "TO_CALL": "Para llamar",
          "TO_PAY": "Para pagar",
          "UPDATE": "Actualización",
          "VALIDATE_PAYMENT_OR_COMMANDS_BY_WAITER":
              "Validar el pago\/Mandatos por el camarero",
          "VAT_INCLUDE_TOTAL": "IVA incluido Total",
          "VIEW_ALL": "Ver todos",
          "WE_WAIT_FOR_YOU_SOON": "Le esperamos pronto.",
          "YES": "Sí",
          "YOUR_ORDER_IS": "Su pedido es",
          "YOUR_PAYMENT_IS": "Su pago es",
          "TOTAL_VAT_INCLUDED": "Total 10% de iva incluido",
          "KIOSK_MODE": "Modo Kiosk",
          "CHOOSE_KIOSK_MODE": "Escoger modo Kiosk ",
          "PRINTER_IP_ADDRESS": "Dirección IP de la impresora",
          "PAY_CHECKOUT_PICK_PRODUCT":
              "Pagar al momento del pago y retirar el producto",
          "PAY_TABLE_DELIVERY_TABLE": "Paga en mesa y entrega en mesa",
          "OFF": "APAGADA",
          "PAY_CHECKOUT_DELIVERY_TABLE":
              "Paga al momento del pago y entrega en la mesa",
          "PAY_CHECKOUT": "PAGAR EN EL PAGO",
          "PAY_TABLE": "PAGAR EN MESA",
          "PICK_PRODUCT": "RECOGER EL PRODUCTO",
          "DELIVERY_TABLE": "ENTREGA EN MESA",
          "AND": "Y",
          "CONNECT_ERROR_PRINTER": "No se pudo conectar a la impresora",
          "IP_ERROR_PRINTER": "IP de la impresora no especificada",
          "USER_CANT_CHANGE_PAYMENT": "Espere hasta que se confirme el pedido",
          "USER_CANT_CHANGE_ORDER": "Espere hasta que se complete el pago",
          "NO_ORDER_PLACED": "Aún no se ha realizado ningún pedido",
          "MODIFICATION": "Modificación",
          "ORDERID": "Solicitar ID",
          "DATE": "FECHA",
          "TIME": "TIEMPO",
          "PHONE_NUMBER": "NÚMERO DE TELÉFONO",
          "LEGAL_NAME": "NOMBRE LEGAL",
          "INVOICE_NUMBER": "Número de factura",
          "CONCEPT": "Concepto",
          "PRICE": "Precio",
          "AMOUNT": "Monto",
          "TAX_BASE_PRINTER": "I.V.A/ TAX BASE 10.00%",
          "TABLE": "MESA",
          "WAY_TO_PAY": "FORMA DE PAGAR",
          "ORDER_RECEIVED": "ORDEN RECIBIDA",
        }
      };
}
