workflows:
  release:
    name: Publish app to playstore and apple store
    max_build_duration: 60
    environment:
      vars:
        PREDEFINED: "true"
        API_URL: https://restaurant-saas-api-new.ionicfirebaseapp.com
        IMAGE_URL_PATH: https://ik.imagekit.io/kplhvthqbi
        ONE_SIGNAL_KEY: Encrypted(Z0FBQUFBQmduaV9JOWRiNWliank0bjRNdjdYUHdDTWw2R09XUkxsb0xSOEkzeV96U1l0eERLLTQ2aF9jcHhjeTdacUktU1FjSlVBTGZVVUlQbXV2ZW1EYThJNERfZEh2S19NTlpqUFFDMDhJNmI3aURZMWtXOExLSFo2MDdVWW1sNndudmhxVzgzeVk=)
        STRIPE_KEY: Encrypted(Z0FBQUFBQmduakFoTlcxbHNiYWF4aEdFUmVqOFdnNldPYjFqc1BIWkdHbTN0WWFlcFNlUmJ5R25MbGZ2OFNvRmRMMmtuSm5maUxPRkd2ek9TWERPQmVfbkFfcnNaNDJuU1N4N0tCT3h4MW9nTy01ZEg2dkU1aHBDQU9VTTBEMFQyT3N1a3I5Z1A1dVQ=)
        ANDROID_GOOGLE_MAP_API_KEY: Encrypted(Z0FBQUFBQmduakJJeldJNFc4eUZVUmZ0b1hGeTktM1Q1RjBqaWlLU0YyaGhuOXhlVTBBM05jeUctam9tenFzWGdpMWdMejRnMFFxNFB4TF9kdm9tSVUxRlNWbHFMbzBfZmZMeDNmbS1rbUtfZGR1SEZNUGh1a2hZZHFCMHJhWXdRcU9OZjdIQnpBMkU=)
        IOS_GOOGLE_MAP_API_KEY: Encrypted(Z0FBQUFBQmduakJJeldJNFc4eUZVUmZ0b1hGeTktM1Q1RjBqaWlLU0YyaGhuOXhlVTBBM05jeUctam9tenFzWGdpMWdMejRnMFFxNFB4TF9kdm9tSVUxRlNWbHFMbzBfZmZMeDNmbS1rbUtfZGR1SEZNUGh1a2hZZHFCMHJhWXdRcU9OZjdIQnpBMkU=)
        STORE_PASSWORD: Encrypted(Z0FBQUFBQmdsUjB3LUpCa1JGaVBqS0x0UXF0MU9yZ1FOajNLdFFvS1p1YjlaMlZXR285YkxhdGFLNlAxTmI3LXRJRWNrWXEtaFM1dTVXbjZoR3dUck9Id3F2UjlaQmpNcXc9PQ==)
        KEY_PASSWORD: Encrypted(Z0FBQUFBQmdsUjB3LUpCa1JGaVBqS0x0UXF0MU9yZ1FOajNLdFFvS1p1YjlaMlZXR285YkxhdGFLNlAxTmI3LXRJRWNrWXEtaFM1dTVXbjZoR3dUck9Id3F2UjlaQmpNcXc9PQ==)
        CERTIFICATE_PRIVATE_KEY: Encrypted(Z0FBQUFBQmZKX1htdHRyVVh1N1pDN3B4M0N2MHhfMGpxNEdhTV9rYnN6RkxLZ0tEZ1YteC1DakNVTWxiYkQwbFhYdDVLbTIwMGdwNEc5cnIzWVBKTlBPUGlLVG1sZktWc1RQakp1WlBQNmc3cFNGWEc3NVA1eXVmRF9yUDhYT25vVUh3cml6d1Bjd2pUU3lSM3lpemNqek0tcUMxSmt5RVh3NDFwbnFGVFpBOHlsN0lxbWt6U2VRb0Vpd3JoQ3pqaFZuZGs4ZnJiNXYyMnpWb2U4LUxPZEtBU3pkZTVkeUFkNkxuaTJpby1pSngzUTFvTjR5dnBjREF2a3BDTjlyQ0hDNTBYNGtaSnZocVZBb1dtcVd3ZzFPZVV6R3ZMaElsZHNRQTN1NU9IR1p4ZGtiUmVRZ3JoRVZobmVzdzF2MzZIV19lZlltejdoYk40Y1huTV96QlI3UnVDemtwQmdWWFdKZkhFTnJlR0F6MTk3OXBYY3d2c2Jra0g1NEVxbDh6dmFoZjBOa0FJbnk3TUxGZVJWbV9SNWhxaDRVSUE0enIwLTBHNHhEWUpyM0xRUUhINEM0Y21VZEY1R0ZKTGJ0ZzdZQnVQYkJvTG9DRzNkMEoxS2xIc0szeEkxY2Myd3BaaldHRGtFMTJ1alpaR3Bzc0oxeENibE9QclN5aENSX2pRcWczVXNLQlRoMmpidGpjbXRwTWI0NjZMMUYyVl9WNVFjVk16U093MHdyNGR5aFBidnNfRHR2eXF2M3BMZm9mNF80cjM0dVR5R19LSF9LMi03dTdjaEJfMFEyS0J4N3F1dF9HbDQ4V0VBUUFReUtkWXQzZ1N3R3l1RFlGczZreno2WllJRklGWmVQTGNpYTBzRTM4TlduVWZyZnRpeW1Wa0VnODhyOHB5clQ1N0w3MlpZdDhZZmZQbVRPaS1VRUZMM2N4R1czdG0wTFQwZFlURGE1Z0wwQzEyVVhBcTg5eDd0bVFiMzFTT0FKN0hTSEFVeUJXMmR2TldIc3JxaFlxaFEwbGhzWFpjREg1bWxJOGw3UjRvYU9WRXVINmMwWjBHR2tGN1RkNFFLUi02bkFvM2lJajhyLVktZFpQWnhRY2w5N3FFd3RBcng0VjMtVkNTaHNPMG9WOHlnWldrUWdaaHpDcV9POVA3S0YyQlNvcFVFdXNmeGs4eTRUV0JRbXJ6UnJscmJETVQ1VGpuRjdoUm9aVVEzRDVVVExWRG45NUhqVlVJVTVQZWxsQnlMQ0xVMng2REp5ZkxmVUg5aDRpaXlqbHhJR21aUm5FZEw2by1vZnlKakR2a2RVQmxxaXp4M1d1UE9BZmtZR3prY1hHbXJDUkhVR2NzT0RSXzA4cXZoa1hnYXdmTG14MDNubVdJZWw0b052cFIyMDU3X0ZCVWFWVmdVa0hiWXk5c2FoLTRrUE5yNHRNTHZFejQ3X241ZzZQVW5icEg4TjRmUV9VX2NhbDlZakFhZy13MXJ5Q1VIVXRMQkVaNEdZYngxd3h3TDYxTjYxRmZIMWx0TVJvcndFLWRRS3dIMUlNbWRuZ1Z2UXd4cFU5dzJSMWxDY2FHamt4MjhfZWVRSmtBd19wRFVRNEZtRXFzNE1YNG9nUDRpeUtPQ3ZaT2xzTm5PaEh0WG9mOVROcjFfaXpGck5OSnNQZ1BIUnZ5TV9XaUZrMzdlYlN6ekM4dFF2Tl9EdXBpUkxqWFNHNW92X0pPdW5OMHZyNW05SFBxUS1peEZsbWVVREhCdkVKa25vZlp1Y2pWalZFY19DVXliT1c0WllpX0FzRVVXZkFEMWp0M2Ytc2xmZHdQN3FxX0E3VUZPVHRYd0FxdjhZaHpqZFpJSmxFOW8yUXg2R0RCWmZtV3gxMmlva1JMRjdnSnNmRG5aSllJQXotZWxMZFRwbmdfMHdLNWM0cTFVZDRoNDg3bW1rX2R3UXB2S3ZLbVN5cFVvaEFxQV9xdDVzR1VQeDJLdGM3RkNKYmlvYWJfRlVyX0gzMmxVRXBSZ1lIVzFwTGxrSTFhMjc0TW96cE5MRkFPMGJVTVZkSlh3RWlhWjhOdS1HT2N2RTE5MVdNd0lGeUVRV2xhOFU5TmhFWjhrUEthR0FtcUNxeUxRR2VEY1ZVZks5Y2k2QmhORUIwZjZweFktWm9paUtsWGhHWXRmVTJTN3BlMldPQ3liclFRLTMtRGFkMzBOVjAyM1o4WVNiSzFKUHdIYnZfbmdodHNzXzBDVVpKcnBHdUQxNEdHNXBPdHJzRDZSRUgtSTNjZDYtaC1xOUdqcE5ydm9kYnFhNHdKZXJNeHZBNE1uQWZnYkgxZ1NVY3J5TW5MRlVXbklvQ1E5R2h4RDVLQUp3Y3BkUnROT0tVVzRXZmtRYUpNaW93WUk3MkJRLTdGNEhqMjFUOWlGRUR6OVhyOGc3UEJVSEdJS05CUi1QaEdWdkRfXzE0N3p5Wk5GRGhWR05RNFR6M2NIbXdEQ3FvRy1ubGJxZkFEZzk3NWN2bVdxbTZVUTlKM0hHOW14VGRaX1V0WTRVMDZkQkQ4cy1ZbG43QW1xb0tGa05xQUFXaENBUUhoTlhRaTBSZmVwTTdidXhlTWIwX1pPd1R4eHF1WVE2WlZKWkpxN1ZITHJzTl9mNzY5bmdPVklCOGZENEFwMy1xTXFCX3RLVHA2U3M3WTRYSmtOVVVEUGNZN3gtbUJaVUtvN0JCVzlkLWlZazRvamdsRk9IRjBkakJPTy1nU1pXLVY0UnVUYUVYWU9XTVpBYV9kUkhQQTQ0ZWF3OTlTYjV1VTEwUXBZRkRyd1M1MFVrUE1Cb2ZwQkhYenVITXU0NmJhb0hFNldoTXdnNEVBNUk5aUg5ZGVjVlQ5aG9UME5WQTI1d19rTjZpRzBIcFpLSlZ5NWVMNWlVcEpIMGoxaHdZNGVnNzRWLXhBR01vNWdNN21wNGF6d2pzT2t1SU8waF8xVlNLMElxZjYtT0FCVk9aUThTMEpjdTJJNTJTbVgyajV0ZXd6S1VmbmRLYVJNMWlYYng3V0hKNi1zOG1YYkhMX1haVjQ5emhhRGswVWlmZ0NfN19ZbjhuelNkT3ZLZm9jSWNF)
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(Z0FBQUFBQmZKX1hteGx1bmd0d2w4M0ltQWp1YTgtOFpvanVCNjZRRmdfV3c4a0NuQVVFUDVCbEVxTWx5ODJTZGJuOTRtVGgwNnJkWjFHY19JbmQ2WHdSQzVDRi12WGp2dUxSOE9NN0VYUF9PY2s5TmZSSngtZnhnbkt2Q3p0bmZmdVdVSmppdXFDamE=)
        APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(Z0FBQUFBQmZKX1htU3AzUXRYSDRxckJQOW5SbXBkb1VRSHFSY0pKZ0RzY1ZZSVdEU1U1X0NiTFV1UEphWW5vRWdtclBiN2JheVYyVGE2Y19sb3NyOXNaUjlScmtLbVMya1E9PQ==)
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(Z0FBQUFBQmZKX1htQzllaFhRMG1LZGEwSXM0WkE4ZVZoZ1NLZkM3S0t4MXNlcW5tMnBPN2hGWi1pSVNia25wR25JM3ZEZWVIZlQ3a2swV2tWVm5OWVdXWDc3YjJDcEt2Z2tYZHFFQU9iRktwZy1HQ2RPZkpWenVMOEljQXU0NGY2aGJYdlVKMUhrRWE0OG5mUEdIVmN2RVlOZFFYLVFSdnNXYmRnTE9Pd1VkeXpzNy03NGMyUFBnNjNFY0R2RzhFTlBsTU8wRkhFU1JUX0pmcDZzWTlib3VQRmg1RDZ4SVcxY19ZaFZyTFBYODl1aGlTdi1vQ2dZZzhTdjhxSlUzWXFzeDVSeWljUTJzUkhkMUhUUkN1ck9PMFFEbTlMckprT290X21RYV9pTXhaVnI1MGhLUHp2WG0xQUp2d29ncEJMQkJMbWNCdmk1R2hFcVpLQllaNHZ1eWtWRFdPQ1QtMF8wZl9mWXJhTXZTdzR0NERsbHJJZjZxMkFkemJJUXQ4TFhiTUg0WThRRTVaQ2paZVEwdGlmYzNHUTROaHVRa0tiZ1prUWhoTUZlTWFIbW5UTHRRTEpsND0=)
        ENV_FILE: Y2F0IDw8RU9UID4+IC5lbnYKUFJFREVGSU5FRD0ke1BSRURFRklORUR9CkFQSV9VUkw9JHtBUElfVVJMfQpPTkVfU0lHTkFMX0tFWT0ke09ORV9TSUdOQUxfS0VZfQpTVFJJUEVfS0VZPSR7U1RSSVBFX0tFWX0KSU1BR0VfVVJMX1BBVEg9JHtJTUFHRV9VUkxfUEFUSH0KSU9TX0dPT0dMRV9NQVBfQVBJX0tFWT0ke0lPU19HT09HTEVfTUFQX0FQSV9LRVl9CkFORFJPSURfR09PR0xFX01BUF9BUElfS0VZPSR7QU5EUk9JRF9HT09HTEVfTUFQX0FQSV9LRVl9CkVPVA==
        JKS_KEY_PROPERTY: Y2F0IDw8RU9UID4+IGFuZHJvaWQva2V5LnByb3BlcnRpZXMKc3RvcmVQYXNzd29yZD0ke1NUT1JFX1BBU1NXT1JEfQprZXlQYXNzd29yZD0ke0tFWV9QQVNTV09SRH0Ka2V5QWxpYXM9a2V5CnN0b3JlRmlsZT0uLi9rZXkuamtzCkVPVA==
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths: []
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: release
          include: true
          source: true
    scripts:
      - flutter upgrade
      - export LC_CTYPE=C; export LANG=C;
      - find ios/Runner/AppDelegate.swift -type f -exec sed -i '' "s|IOS_GOOGLE_MAP_API_KEY|$IOS_GOOGLE_MAP_API_KEY|g" {} \;
      - echo $ENV_FILE | base64 --decode > env
      - sh env
      - echo $JKS_KEY_PROPERTY | base64 --decode > keys
      - sh keys
      - flutter packages pub get
      - flutter pub run build_runner build --delete-conflicting-outputs
      - flutter build appbundle --target-platform android-arm,android-arm64,android-x64
      - find . -name "Podfile" -execdir pod install \;
      - keychain initialize
      - app-store-connect fetch-signing-files "com.ioicfirebaseapp.fooddeliverysystem" --type IOS_APP_STORE --create
      - keychain add-certificates
      - flutter build ios --release --no-codesign
      - xcode-project use-profiles
      - xcode-project build-ipa --workspace "ios/Runner.xcworkspace" --scheme "Runner"
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - pietechsolution@gmail.com
          - kakadiyasandip4world@gmail.com
          - ujjwal.2518@gmail.com
          - montyvipul@gmail.com
          - nidhi@pietechsolution.com
          - sarth@pietechsolution.com
      app_store_connect:
        # app_id: "1566547500"
        apple_id: pietechsolution@gmail.com
        password: Encrypted(Z0FBQUFBQmZKX1p3WU1obl9mTjBSa0tBOWpqSlRoNzBvVk53Vzl4eFpGRm5OVVdsVW5zbnFETThEaTBoNEhQdGJZb2Itc2I5SmlmTnVuRktxRWdmWEo4dFdWOXRVd2xrdXJHY1NlZHg3ZzBjZ21WbldlaF9QZTQ9)
      google_play:
        credentials: Encrypted(Z0FBQUFBQmZEVlM4MUFGX0RjVHIzLUl0LTU5YnF1a2xZOTVIZlMxZFNMYVN6NTlVdm5nSU82ZloyRmo2bmttakkyOVlQREFpanFqTDNGV092ZHVqOXlFRGRlT1NmVThOR0VpMzhkcnpkRzRya01BcjRUd2ktRjV3bEpvQnhKQU5lY3FtbjRCeUpCOV9ZRl95aU5paDVkdm5ITmxQTXdHSFBIZmFHck5aeXVGQ0xlOE9JdFVXVGhTd2hsWWZTMjR2SUJoQy1rc0d0YTNyZ3F1ZmpiVDItNldoM3BoclpZSkVXVzNvYUhldk4taGJFUWZJZWRQWENXT0plQ3A4ZmJSVXN4REktTVhSTGF1M2RjWlp6M194Zk9xVzlYQUxFbG4wbGxrUDUxcUItSkJna25RcVVSVUdNek44TEVlbGdZQWJ4dDZoWFZxd2ljOEdnZG9WY290cTFxYnR1S2NmZ3hPeWdWaTkzTkctamh5WVIwWkowTUtyRFpUOXdzck5GdjZibFdUd2Rza3ZmLUNKSUN3UjEzdzVYd3RQRUt3M2Z5LUZXaHcyZXJMYUNtVmQ3dDN3UUN1RDA0aEQyckpfa01TR01GVW1pRlZINlBmVVgzV3BIZGJJUUVtWDJEVmVuVTFPZ29lVlZOOC1BTGphMDR2TmVWNDZlRjhGRFh2V0p3akJjSGc4akpCeGFpYTBzYWtkSzNMUnZjUC16OGltM1BhMUc0eFM3UjVXX0sya2QxMmFjSVlnb1V4MWhXYzllYUticVpaVnRoenNZUDB5Z2Y2eEhiRVh6RGVHei1LVl96bmE4LTVBMXZhaVN1a011d2I3eXF4bjZZTFY4MDNmX2Z3TkVtYTNlaEdGZXJ2YlkySDdIcE93UGNXZmd2TWdtcXNiOVhIZXYtSVBnaUJpb3paQXk3bHVEeFYzSGVJeFRpcHVHbnk5cXoyblpVZTBiTlR1UDJndExzdm5uMGhuMHA2dWJIbG05a0xBQ2dTVTNHNkJ3VWxXd2NwUktES254QXRLdGhKeVRHVEd0dzhWazVLd1hhR2NnMVNObXQwWFlKRk1VZUZ6QVpnMWdENjY0VVBhaE1oNndWU3JaTm1faVBJemRhWF84bWJ1TjJPTzd2dGVTN05tS0pMc2s4eFRxbjYtQndNblNvQlpxUWxFaXRSX3JDc2hZLW4tZWZfcEFlVmhhUXlEQi1uYURhWUpKei1yZEl2eVVjVlFNN1BUUndRazBWTjZUMmE4TVVHMTZoVXlMTzZUV2QxbWcyQVVyUFVIWEJFcmoxbHd4a2tqS2NvUDhEU3hjazRMWlBaNG54LWxYbFlnWHFMemFjcXdsNWhMQ2tyaVRoaERDZzFrNVNhSzBwc1dwMHFJbzRRMmJFdlFWcVdhMmhMbEVUcHk1NF90S01ZWlFfY21HVHdIVmx2WVZ5aU9yY3d2X2VWeGdxek5JaTZvVVFlNl9lQ25lMHJXRE5yMDd3RnRjaUJjY1hwbXJrQUtvb2dXcThhU2dyLUxoRWRSeHZHM0kyY0NrVVFYWDgza2NIaUJZTXh2U2dXOTN3a0NyazkzTDhxampoNDRQTHRtS2lhRW1mU2hlcVdhbWhhbnVVUEpHd3lNS0JtQnlsT1c1djljM2RsTGx3X3VJWkNJOXYtVWlwdkxjUkdEX3dTUmpmNkZOOHRWeThtNWxoWGNLdEFmZ0NBZm1nTHhvSmg4MW5rSEd0TUE4WkVZdUdHOGpDOWFWZHd6SF9EQW1wUDJqZXZKVnlpX040Wmg5Q1o2YXR2dWIybDJkbnVlTUhsd3kydU5CcUNiY1ZtTXZObEpjM2RuTFROVWQzZ3VONkppUDlJWG9lTl9lQmhxcEItZFNMWTVQV1hKOElyZWZReWZydDFEM3M2Um1rOTJtY1l4RktpYk9vcGZQOVp2TVRhRTVobmFJX3l2NHFYTXB4WGlBb2JLSkt5RkFDSDFsenZsMzY1S095a0h2YWgyTENHWE83LWxCbUhpUlduN2NXUDM0a2k3YTZIaFlVYlpqWC05SzhxVDFsaGJpVldRWHkxdTZlVUVFSEN5RmNxS1prdHE4WVJqNEhRaTVPdTVNSmtfdEduMHEtd1B5cnBHZzZBV05IeGFYckk2aTU0eDl5SGZyZHRnS250UU4zNFRET2VjZFNTY05ZbXc4RFdnUl83YmlnbnBtOGFrY1NFQkRBSVRxTzBiSUxiX1F5eEY3aHk0dU5pRW1Ra2hIM3owS01BczYwYm1TVkFZVzRINkVubm9wM1JNbTFZRGItc0xmZ0wzY2ZBbWhzajRxNS14VzBwc0sxN1ZMRTI1VGJkTGJPUFctZEt5bjV4TEZsejA5a1VZdXJMcWdYZlRxOWhKckdWbVlISmFCc2xjLTJLcVRTbzg3R3BQZm1kU05ld3BLcE5wZGd3Y0lLWXNlS3hRMFFUeDZ5S3JhNDhUb1pSbnRnRnRpZ1VKSTJLQlZrNnZYVzU1NUlmSDlrX193XzNnNVJlNnJkZGladDZSMmNGemd2WjIzT0JueG9ranBVVzRtS3BKVHE1NlZ5OElXT2RtS2UyYkQ2dGZ4cnVhVGQ3bXRscWM0OTFjczktYUM1ZXg5ZVZGX1J5a0djcWZPYnNiZmF3R3RfODV6WV9jRFktcHR4M0tNWk1aSWtNU1pXZUx6WG84YUdtdy1SN1BRcC1MQ2NpMWRaSVJjckxiZmlNVkJfM3NEaWNJS004eF9OdWxfcHg1cXFhdzZUYkZMMWlYdTdzTzJtY0RkRmlha3JtQ1NGNVV3N0hFeWhTbDdaZy11VHV1ZV9yY2UxRVBoQmpzRl9QWHJ5ZnJ2UXl4cWRzS2plQ28xSVdjdHZYeFhUQVlWbTZXYnhVOVVZZXlYdXR1aUNtNko4U1lMZzlEcllQMTJOOUNCV2NnSEx3d0FfN0xvOGNrbjAtVjN1M3JsQk9pUlhRb2MtYTM0WFp0YWxvZU9hLTZLTUZTSUs2LUhpYTJScTJhTHdoSTJLWnVIMWE3MUdhbGhOOXVMUzJWODBFZ0FkajJVMlhMVzkwMERqYmNLLW9wc1RDSklCVXNfZzlHMzJCZERZRVpPaGFCZWxvcjFXUGI3U3ZLbGstY1VrdWJfcVhiaTN4aDN0R21rcnhaWTY3WU1yakNEWTBFNk9PYzBnY2xJU1BnZTBCWTF1VlZJS0NlT1RWVm44LXNIM25CWDhOYy1XU01nSjFOLWliSXV1WGpfWk5fclBEWFd0ZzFrTktTZ2N1M25GYU0wOXlBUDJsZlNMaldEUk9QclNfVTRoOHRDYWdETnV5cy1pQkRIRVVBWDBSMUN0cnBrdHNRcHE1UGRNVENCdnFEVk9FQTBtZ2JyeHdWeTdJcm8yM2JlMDlhNThRTU0xRnhtRjVZOUNnM2VSeXZaQlFVQ3RVSlpPbUFpcTVpMVp2MTdTaEszekZ0UEF2VjA5NG1Bd2lKYjJ0ZldtUE1zWWtPT1JBS3JXR0xuY19WMlB3VS1wWG1IM3p2T2VVRUNOM2RlU1pOQjRWTmJjclBTTGRhV2g0TkRVemdWNUdBQ2w3eE5qbzFVZ3Utd1ptSHZzakEtbmg2LW9EZXNZMkx5MmJwTHlTcXBLOXk3MmZqTkJEUEJ4QzNBOVZlczVoeE5nTHIwN0VSZVRFcUNFUkhvNzFLREsxMlBHVG5KSEdjMktpTnVFZENsSGQ3UzNpbUdrMVo0WFlqOFNDbzFOaVdmZWhHbS16TlpBdVQzSFNnVzRyczFWSTRtSzFJdXBzazRtRHZlUTluXzN2NGRpSElpQTl5SlhSU0syM0o4bVBXUHFmOUJEQVVnV3VJdnQ2V0JCRDRCcE5PREJraXA5bG1lNXdHSE1ocnh6RXlYTm82dWs3VnhCdEZDSTk1clluM0o4d2dsZENrank4SGxHdURoakFZT1o0MDRyQ0hTbzBubjVaQjI2eXotQ2RXbVZEb1IteVF1bURaOHpQTDd3TGxGT2p3NjE1OEVFSE1DNWJDUkpaVDhrbVI1SjFTNld6QWhHMTluSndDcWpnT0VGY3R2XzlNeWVOTGFIazVFcWZVVjJHNkhwMEx6LW5Bb1JfM0ZOYjM5OFBWUWtUX2M2Y3ltaS1aeFVZNWlkVDVjbUZleEJfMV9rOWk4M21mWDg1d3BDZzJUYmNIM21vc3daX1hTSHNJZjc3a0V1dFhGQjRRdEZnalVxdnBqY2dfRlF0Z0stTGNtMFRZUXFnM1U0QmtvQlRsYTNpcHhuYTNWdUZLX19JSzJ6UEVyOEFfMmJsWVBfTjc3clNnNE5FTUZtZmNmNnUzb1k5ajBnPT0=)
        track: production

  production:
    name: Create Production APK for testing
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        PREDEFINED: "true"
        API_URL: https://restaurant-saas-api-new.ionicfirebaseapp.com
        IMAGE_URL_PATH: https://ik.imagekit.io/kplhvthqbi
        ONE_SIGNAL_KEY: Encrypted(Z0FBQUFBQmduaV9JOWRiNWliank0bjRNdjdYUHdDTWw2R09XUkxsb0xSOEkzeV96U1l0eERLLTQ2aF9jcHhjeTdacUktU1FjSlVBTGZVVUlQbXV2ZW1EYThJNERfZEh2S19NTlpqUFFDMDhJNmI3aURZMWtXOExLSFo2MDdVWW1sNndudmhxVzgzeVk=)
        STRIPE_KEY: Encrypted(Z0FBQUFBQmduakFoTlcxbHNiYWF4aEdFUmVqOFdnNldPYjFqc1BIWkdHbTN0WWFlcFNlUmJ5R25MbGZ2OFNvRmRMMmtuSm5maUxPRkd2ek9TWERPQmVfbkFfcnNaNDJuU1N4N0tCT3h4MW9nTy01ZEg2dkU1aHBDQU9VTTBEMFQyT3N1a3I5Z1A1dVQ=)
        ANDROID_GOOGLE_MAP_API_KEY: Encrypted(Z0FBQUFBQmduakJJeldJNFc4eUZVUmZ0b1hGeTktM1Q1RjBqaWlLU0YyaGhuOXhlVTBBM05jeUctam9tenFzWGdpMWdMejRnMFFxNFB4TF9kdm9tSVUxRlNWbHFMbzBfZmZMeDNmbS1rbUtfZGR1SEZNUGh1a2hZZHFCMHJhWXdRcU9OZjdIQnpBMkU=)
        IOS_GOOGLE_MAP_API_KEY: Encrypted(Z0FBQUFBQmduakJJeldJNFc4eUZVUmZ0b1hGeTktM1Q1RjBqaWlLU0YyaGhuOXhlVTBBM05jeUctam9tenFzWGdpMWdMejRnMFFxNFB4TF9kdm9tSVUxRlNWbHFMbzBfZmZMeDNmbS1rbUtfZGR1SEZNUGh1a2hZZHFCMHJhWXdRcU9OZjdIQnpBMkU=)
        STORE_PASSWORD: Encrypted(Z0FBQUFBQmdsUjB3LUpCa1JGaVBqS0x0UXF0MU9yZ1FOajNLdFFvS1p1YjlaMlZXR285YkxhdGFLNlAxTmI3LXRJRWNrWXEtaFM1dTVXbjZoR3dUck9Id3F2UjlaQmpNcXc9PQ==)
        KEY_PASSWORD: Encrypted(Z0FBQUFBQmdsUjB3LUpCa1JGaVBqS0x0UXF0MU9yZ1FOajNLdFFvS1p1YjlaMlZXR285YkxhdGFLNlAxTmI3LXRJRWNrWXEtaFM1dTVXbjZoR3dUck9Id3F2UjlaQmpNcXc9PQ==)
        ENV_FILE: Y2F0IDw8RU9UID4+IC5lbnYKUFJFREVGSU5FRD0ke1BSRURFRklORUR9CkFQSV9VUkw9JHtBUElfVVJMfQpPTkVfU0lHTkFMX0tFWT0ke09ORV9TSUdOQUxfS0VZfQpTVFJJUEVfS0VZPSR7U1RSSVBFX0tFWX0KSU1BR0VfVVJMX1BBVEg9JHtJTUFHRV9VUkxfUEFUSH0KSU9TX0dPT0dMRV9NQVBfQVBJX0tFWT0ke0lPU19HT09HTEVfTUFQX0FQSV9LRVl9CkFORFJPSURfR09PR0xFX01BUF9BUElfS0VZPSR7QU5EUk9JRF9HT09HTEVfTUFQX0FQSV9LRVl9CkVPVA==
        JKS_KEY_PROPERTY: Y2F0IDw8RU9UID4+IGFuZHJvaWQva2V5LnByb3BlcnRpZXMKc3RvcmVQYXNzd29yZD0ke1NUT1JFX1BBU1NXT1JEfQprZXlQYXNzd29yZD0ke0tFWV9QQVNTV09SRH0Ka2V5QWxpYXM9a2V5CnN0b3JlRmlsZT0uLi9rZXkuamtzCkVPVA==
    cache:
      cache_paths: []
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master-build
          include: true
          source: true
    scripts:
      - flutter upgrade
      - export LC_CTYPE=C; export LANG=C;
      - echo $ENV_FILE | base64 --decode > env
      - sh env
      - echo $JKS_KEY_PROPERTY | base64 --decode > keys
      - sh keys
      - flutter packages pub get
      - flutter pub run build_runner build --delete-conflicting-outputs
      - flutter build apk --release
    artifacts:
      - build/**/outputs/apk/release/app-release.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - pietechsolution@gmail.com
          - kakadiyasandip4world@gmail.com
          - ujjwal.2518@gmail.com
          - montyvipul@gmail.com
          - nidhi@pietechsolution.com
          - sarth@pietechsolution.com

  testing:
    name: Create Staging APK for testing
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        PREDEFINED: "true"
        API_URL: https://restaurant-saas-api-new-stg.ionicfirebaseapp.com
        IMAGE_URL_PATH: https://ik.imagekit.io/kplhvthqbi
        ONE_SIGNAL_KEY: Encrypted(Z0FBQUFBQmduaV9JOWRiNWliank0bjRNdjdYUHdDTWw2R09XUkxsb0xSOEkzeV96U1l0eERLLTQ2aF9jcHhjeTdacUktU1FjSlVBTGZVVUlQbXV2ZW1EYThJNERfZEh2S19NTlpqUFFDMDhJNmI3aURZMWtXOExLSFo2MDdVWW1sNndudmhxVzgzeVk=)
        STRIPE_KEY: Encrypted(Z0FBQUFBQmduakFoTlcxbHNiYWF4aEdFUmVqOFdnNldPYjFqc1BIWkdHbTN0WWFlcFNlUmJ5R25MbGZ2OFNvRmRMMmtuSm5maUxPRkd2ek9TWERPQmVfbkFfcnNaNDJuU1N4N0tCT3h4MW9nTy01ZEg2dkU1aHBDQU9VTTBEMFQyT3N1a3I5Z1A1dVQ=)
        ANDROID_GOOGLE_MAP_API_KEY: Encrypted(Z0FBQUFBQmduakJJeldJNFc4eUZVUmZ0b1hGeTktM1Q1RjBqaWlLU0YyaGhuOXhlVTBBM05jeUctam9tenFzWGdpMWdMejRnMFFxNFB4TF9kdm9tSVUxRlNWbHFMbzBfZmZMeDNmbS1rbUtfZGR1SEZNUGh1a2hZZHFCMHJhWXdRcU9OZjdIQnpBMkU=)
        IOS_GOOGLE_MAP_API_KEY: Encrypted(Z0FBQUFBQmduakJJeldJNFc4eUZVUmZ0b1hGeTktM1Q1RjBqaWlLU0YyaGhuOXhlVTBBM05jeUctam9tenFzWGdpMWdMejRnMFFxNFB4TF9kdm9tSVUxRlNWbHFMbzBfZmZMeDNmbS1rbUtfZGR1SEZNUGh1a2hZZHFCMHJhWXdRcU9OZjdIQnpBMkU=)
        STORE_PASSWORD: Encrypted(Z0FBQUFBQmdsUjB3LUpCa1JGaVBqS0x0UXF0MU9yZ1FOajNLdFFvS1p1YjlaMlZXR285YkxhdGFLNlAxTmI3LXRJRWNrWXEtaFM1dTVXbjZoR3dUck9Id3F2UjlaQmpNcXc9PQ==)
        KEY_PASSWORD: Encrypted(Z0FBQUFBQmdsUjB3LUpCa1JGaVBqS0x0UXF0MU9yZ1FOajNLdFFvS1p1YjlaMlZXR285YkxhdGFLNlAxTmI3LXRJRWNrWXEtaFM1dTVXbjZoR3dUck9Id3F2UjlaQmpNcXc9PQ==)
        ENV_FILE: Y2F0IDw8RU9UID4+IC5lbnYKUFJFREVGSU5FRD0ke1BSRURFRklORUR9CkFQSV9VUkw9JHtBUElfVVJMfQpPTkVfU0lHTkFMX0tFWT0ke09ORV9TSUdOQUxfS0VZfQpTVFJJUEVfS0VZPSR7U1RSSVBFX0tFWX0KSU1BR0VfVVJMX1BBVEg9JHtJTUFHRV9VUkxfUEFUSH0KSU9TX0dPT0dMRV9NQVBfQVBJX0tFWT0ke0lPU19HT09HTEVfTUFQX0FQSV9LRVl9CkFORFJPSURfR09PR0xFX01BUF9BUElfS0VZPSR7QU5EUk9JRF9HT09HTEVfTUFQX0FQSV9LRVl9CkVPVA==
        JKS_KEY_PROPERTY: Y2F0IDw8RU9UID4+IGFuZHJvaWQva2V5LnByb3BlcnRpZXMKc3RvcmVQYXNzd29yZD0ke1NUT1JFX1BBU1NXT1JEfQprZXlQYXNzd29yZD0ke0tFWV9QQVNTV09SRH0Ka2V5QWxpYXM9a2V5CnN0b3JlRmlsZT0uLi9rZXkuamtzCkVPVA==
    cache:
      cache_paths: []
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: testing-build
          include: true
          source: true
    scripts:
      - flutter upgrade
      - export LC_CTYPE=C; export LANG=C;
      - echo $ENV_FILE | base64 --decode > env
      - sh env
      - echo $JKS_KEY_PROPERTY | base64 --decode > keys
      - sh keys
      - flutter packages pub get
      - flutter pub run build_runner build --delete-conflicting-outputs
      - flutter build apk --release
    artifacts:
      - build/**/outputs/apk/release/app-release.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - pietechsolution@gmail.com
          - kakadiyasandip4world@gmail.com
          - ujjwal.2518@gmail.com
          - montyvipul@gmail.com
          - nidhi@pietechsolution.com
          - sarth@pietechsolution.com
